version: '3.8'

services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: sh -c "npm install && npm run build && npm start"
